### ISSUE TITLE
I ran into an error, but I can't figure out a way to get around it. 

### ISSUE THREAD

**Issue by loneblues** [gsmartensson/avra_public#2]
I tried to run AVRA. I checked that FSL 6.0 is properly installed, and the $FSLDIR worked find. However, the below error message keeps being printed. Do you have an idea? 
Thanks in advance. 

Performing rigid registration of input image to MNI template (AC-PC alignment)
230305-04:24:05,262 nipype.interface INFO:
         stderr 2023-03-05T04:24:05.262855:/home/loneblues/fsl/bin/fslreorient2std: 1: bc: not found
230305-04:24:05,318 nipype.interface INFO:
         stdout 2023-03-05T04:24:05.318521:Cannot perform requested swap (NEUROLOGICAL/RADIOLOGICAL storage inverted)
230305-04:24:05,318 nipype.interface INFO:
         stdout 2023-03-05T04:24:05.318521:Try the following command instead:
230305-04:24:05,320 nipype.interface INFO:
         stdout 2023-03-05T04:24:05.320094:fslswapdim t1 RL PA IS test/test1_tmp.nii
Traceback (most recent call last):
  File "/home/loneblues/.local/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
    setattr(outputs, key, val)
  File "/home/loneblues/.local/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/home/loneblues/.local/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/home/loneblues/.local/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'out_file' trait of a Reorient2StdOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/mnt/j/enigma/synth_test/ct_synthseg_test_MRcomp/t1/test/test1_tmp.nii' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/j/enigma/avra_public/avra.py", line 81, in <module>
    native_to_tal_fsl(args.input_file, force_new_transform=args.registration,dof=dof,output_folder =args.output_dir,guid=args.uid)
  File "/mnt/j/enigma/avra_public/utils/misc.py", line 153, in native_to_tal_fsl
    fsl_pre.run()
  File "/home/loneblues/.local/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 401, in run
    outputs = self.aggregate_outputs(runtime)
  File "/home/loneblues/.local/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/mnt/j/enigma/synth_test/ct_synthseg_test_MRcomp/t1/test/test1_tmp.nii' for output 'out_file' of a Reorient2Std interface

**Comment by loneblues** [comment]
OK it appears that I did'nt manage to install a few dependencies. My bad. Thanks!
